### ISSUE TITLE
iOS Notification Badge Does Not Clear

### ISSUE THREAD

**Issue by ValerioParisMitritsakis** [gitterHQ/gitter#1299]
I you get a notification badge on your iOS and read the actual messages on another client (say on OS X) there is not to clear the badge unless you get a new message and read it on your iOS device.

When you open the app it should clear the badges if there are no unread messages.

**Comment by mydigitalself** [comment]
@trevorah There seem to be some issues with this, was just testing it. I had (2) badges on my icon. Opened the desktop app, read messages in one room, and the badge successfully moved down to (1). Opened the second room and the badge stayed on (1).

Opening the app, it's still at (1). Pull to refresh. Still at (1).

So perhaps it's getting stuck at (1) ?

@ValeroParisMitritsakis are you seeing the same thing - the badge is stuck on (1) ?

**Comment by ValerioParisMitritsakis** [comment]
I had it stuck at (1), when it was (2) I opened it on iOS instead of the desktop app to see if it would clear (which it did) so I do not know if it would also get stuck on more than (1) had I opened the desktop app at the time.

**Comment by mydigitalself** [comment]
Mine ended up clearing just fine, but @hilton seems to have a similar issue. @trevorah can you please investigate further.

**Comment by trevorah** [comment]
On it!

FYI we have two things that update the ios app badge:

1. we send a push notification with the badge number (usually silently) from the server, although this is a little bit of a dark art due to performance optimisations. This also doesnt require the ios app to be running.
2. when the app is running, it has a live query (roughly `SELECT COUNT(*) FROM rooms WHERE mentions > 0 OR unreadItems > 0`) on the local database so that if you read a message then the app badge is immediately updated without waiting for push notifications. This should match exactly what is in the phone's room list as it shares the same database.

If they are both consistently wrong then this is going to be quite interesting. I'll start with (2) first as if it's reproducible it will be the easiest to track down.

**Comment by hilton** [comment]
For what it’s worth, the persistent bogus `1` badge I had lasted a few days despite various efforts (restart phone, reinstall iOS app) and then even more mysteriously went away. I couldn’t tell what was different, although if I had to guess, I’d say it was shortly after username mentions.

**Comment by dregad** [comment]
Just a note to say that I'm suffering from the same issue on my iPhone as well. For the past 6-7 days, I have an unread (1) badge that just won't go away, no matter what I do. I applied the same tricks as @hilton above, but without success. In an attempt to mark them as read, I also tried (in the browser) to scroll back up to the most recent @ notifications in all subscribed rooms, but that did not help either.

**Comment by trevorah** [comment]
I've pushed an ios release that will fix the mismatch when the app is opened and im currently looking at why we sending push notifications with the wrong badge number.

**Comment by ValerioParisMitritsakis** [comment]
Thank you so much for the fix. If it helps you I notiiced this happens even when I went into the app read the messages and got out. Then I went back in again and the badge number went away. It was initially two and got to one the first time I exited. The second time it disappeared

**Comment by trevorah** [comment]
Found it. The push notification library we were using had accidentally introduced a bug, but it has since been fixed (https://github.com/argon/node-apn/pull/394, thanks @artemsmirnov!). The fix hasnt been released yet, so I'm rolling back to an earlier version.

**Comment by trevorah** [comment]
The new server instances are now running and I can confirm that the badges can finally reach 0. Thanks everyone for reporting and have a good weekend! 🎉

**Comment by GaryKing** [comment]
Anything we need to do on our end? Mine's still showing 1 and I definitely have no notifications because I'm only in one room and I already "marked all as read" on it.

**Comment by trevorah** [comment]
@GaryKing as the ios app update is still waiting to be approved by apple, you will have to receive a new message for the badge number to be corrected. I'll send you a message now.

**Comment by GaryKing** [comment]
I got your message. I still have the "1" badge. I'll wait until the app update then report back.
